

module.exports = "CREATE TABLE IF NOT EXISTS Uploads (" +
    "UploadId INT NOT NULL AUTO_INCREMENT," +
    "FileType VARCHAR(255)," +
    "Url VARCHAR(255)," +
    "CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP," +
    "PRIMARY KEY (UploadId));"